// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PartyPlanner.Infrastructure.Data;

#nullable disable

namespace PartyPlanner.Infrastructure.Migrations
{
    [DbContext(typeof(PartyPlannerDbContext))]
    [Migration("20260325200853_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PartyPlanner.Core.Entities.Guest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid?>("PartyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("PartyId");

                    b.ToTable("Guests", (string)null);
                });

            modelBuilder.Entity("PartyPlanner.Core.Entities.Party", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Parties", (string)null);
                });

            modelBuilder.Entity("PartyPlanner.Core.Entities.PartyTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Assignee")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<bool>("Done")
                        .HasColumnType("bit");

                    b.Property<Guid?>("PartyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("PartyId");

                    b.ToTable("Tasks", (string)null);
                });

            modelBuilder.Entity("PartyPlanner.Core.Entities.Guest", b =>
                {
                    b.HasOne("PartyPlanner.Core.Entities.Party", null)
                        .WithMany("Guests")
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PartyPlanner.Core.Entities.Party", b =>
                {
                    b.OwnsOne("PartyPlanner.Core.Entities.Budget", "Budget", b1 =>
                        {
                            b1.Property<Guid>("PartyId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Estimated")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("BudgetEstimated");

                            b1.Property<decimal>("Spent")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("BudgetSpent");

                            b1.HasKey("PartyId");

                            b1.ToTable("Parties");

                            b1.WithOwner()
                                .HasForeignKey("PartyId");

                            b1.OwnsMany("PartyPlanner.Core.Entities.BudgetItem", "Items", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("decimal(18,2)");

                                    b2.Property<string>("Category")
                                        .IsRequired()
                                        .HasMaxLength(80)
                                        .HasColumnType("nvarchar(80)");

                                    b2.Property<string>("Label")
                                        .IsRequired()
                                        .HasMaxLength(150)
                                        .HasColumnType("nvarchar(150)");

                                    b2.Property<Guid>("PartyId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.HasKey("Id");

                                    b2.HasIndex("PartyId");

                                    b2.ToTable("BudgetItems", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("PartyId");
                                });

                            b1.Navigation("Items");
                        });

                    b.Navigation("Budget")
                        .IsRequired();
                });

            modelBuilder.Entity("PartyPlanner.Core.Entities.PartyTask", b =>
                {
                    b.HasOne("PartyPlanner.Core.Entities.Party", null)
                        .WithMany("Tasks")
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PartyPlanner.Core.Entities.Party", b =>
                {
                    b.Navigation("Guests");

                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
