// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using PartyPlanner.Infrastructure.Data;

#nullable disable

namespace PartyPlanner.Infrastructure.Migrations
{
    [DbContext(typeof(PartyPlannerDbContext))]
    [Migration("20260518000300_AddGuestInvitationToken")]
    partial class AddGuestInvitationToken
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
